/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.3.144 */
/* Module Version: 5.7 */
/* Fri Nov 27 00:51:52 2020 */

/* parameterized module instance */
clk_cfg __ (.CLKI( ), .CLKOP( ), .CLKOS( ));
