LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := hello_ndk_build
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := hello.cpp

LOCAL_CFLAGS := -DDEBUG -Werror

# LOCAL_SHARED_LIBRARIES :=
# include $(BUILD_SHARED_LIBRARY)
include $(BUILD_EXECUTABLE)