BASEINCLUDE ?= /home/parallels/workspace/project/linux-5.3.8
robin_demo_mmap-objs := robin_mmap.o

obj-m := robin_demo_mmap.o

all :
	$(MAKE) -C $(BASEINCLUDE) M=$(PWD) modules;

clean:
	$(MAKE) -C $(BASEINCLUDE) SUBDIRS=$(PWD) clean;
	rm -f *.ko
