# SPDX-License-Identifier: GPL-2.0-only
obj-n += algorithem/
obj-n += thread/
obj-n += sysfs/
obj-n += dts/
obj-$(CONFIG_BISCUITOS_I2C) += i2c/
obj-$(CONFIG_BISCUITOS_SPI) += spi/
obj-$(CONFIG_BISCUITOS_MIPI) += mipi/
