# SPDX-License-Identifier: GPL-2.0-only
obj-y += algorithem/
obj-y += thread/
obj-y += sysfs/
obj-y += dts/
obj-$(CONFIG_BISCUITOS_I2C) += i2c/
obj-$(CONFIG_BISCUITOS_SPI) += spi/
obj-$(CONFIG_BISCUITOS_MIPI) += mipi/